print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/miles/Documents/GitHub/GalleryDemo/Assets/basicCrownMol.ma"`)
{		
	file -o "/Users/miles/Documents/GitHub/GalleryDemo/Assets/basicCrownMol.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/miles/Documents/GitHub/GalleryDemo/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/miles/Documents/GitHub/GalleryDemo/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/miles/Documents/GitHub/GalleryDemo/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
